name: peruvian_recipes_flutter
description: "Flutter mobile application for the 'Súper Recetas Peruanas' project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc_test: ^9.1.7
  cloud_firestore: ^5.0.2
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_analytics: ^11.1.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_messaging: ^15.0.2
  firebase_storage: ^12.1.0
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.1.2
  google_sign_in: ^6.2.1
  injectable: ^2.4.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  mockito: ^5.4.4
  mocktail: ^1.0.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  intl_utils: ^2.8.7
  melos: ^6.1.0

flutter:
  uses-material-design: true

  #assets:
  #  - assets/
  #  - assets/images

flutter_intl:
  enabled: true
  class_name: L
  arb_dir: lib/core/localizations
  output_dir: lib/core/localizations
  output_localization_file: l10n.dart
  output_class: AppLocalizations
  synthetic_package: false
  nullable_getter: false
  main_locale: es
